// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ognsspoevwaolkdliavh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbnNzcG9ldndhb2xrZGxpYXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNTMwNDYsImV4cCI6MjA1NjYyOTA0Nn0._H4Wt-j6g-am3lPOQOpzafrcBlH7GA_mOR0YtcVvGSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);